"""
Developer Assistance Module
Provides project scaffolding and code generation capabilities.
"""
import os
import subprocess
from pathlib import Path
from datetime import datetime


def _build_result(action, path, status, message, item_type="Project", extra=None):
    return {
        "action": action,
        "name": Path(path).name if path else "",
        "path": str(Path(path).expanduser().resolve()) if path else "",
        "type": item_type,
        "status": status,
        "message": message,
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "details": extra,
    }


def _ensure_dir(path):
    path = Path(path).expanduser()
    path.mkdir(parents=True, exist_ok=True)
    return path


def create_python_project(name, base_dir=None):
    """Create a Python project structure with main.py, requirements.txt, README.md."""
    base = Path(base_dir or Path.cwd()).expanduser() / name
    try:
        _ensure_dir(base)
        # main.py
        main_py = base / "main.py"
        if not main_py.exists():
            main_py.write_text(
                f'"""\\n{name} - Python Project\\nGenerated by AMAZON AI Assistant\\n"""\\n\\n\\ndef main():\\n    print("Hello from {name}!")\\n\\n\\nif __name__ == "__main__":\\n    main()\\n',
                encoding="utf-8"
            )
        # requirements.txt
        req = base / "requirements.txt"
        if not req.exists():
            req.write_text("# Add project dependencies here\n", encoding="utf-8")
        # README.md
        readme = base / "README.md"
        if not readme.exists():
            readme.write_text(
                f"# {name}\\n\\nA Python project generated by AMAZON AI Assistant.\\n\\n## Getting Started\\n\\n```bash\\npip install -r requirements.txt\\npython main.py\\n```\\n",
                encoding="utf-8"
            )
        # src folder
        _ensure_dir(base / "src")
        (base / "src" / "__init__.py").write_text("", encoding="utf-8")
        # tests folder
        _ensure_dir(base / "tests")
        (base / "tests" / "__init__.py").write_text("", encoding="utf-8")
        test_file = base / "tests" / "test_main.py"
        if not test_file.exists():
            test_file.write_text(
                '"""Tests for main module."""\\n\\n\\ndef test_placeholder():\\n    assert True\\n',
                encoding="utf-8"
            )
        return _build_result("Created Project", base, "success",
                             f"Python project '{name}' created at {base}",
                             "Python Project",
                             {"framework": "python", "files": ["main.py", "requirements.txt", "README.md", "src/", "tests/"]})
    except Exception as e:
        return _build_result("Create Project", base, "failed", str(e), "Python Project")


def create_react_project(name, base_dir=None):
    """Create a React project using create-react-app (requires Node.js)."""
    base = Path(base_dir or Path.cwd()).expanduser()
    target = base / name
    try:
        # Check if Node.js is available
        result = subprocess.run(
            ["node", "--version"], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return _build_result("Create Project", target, "failed",
                                 "Node.js is not installed. Install Node.js to create React projects.",
                                 "React Project")

        # Use npx create-react-app
        subprocess.run(
            ["npx", "--yes", "create-react-app", name],
            cwd=str(base), capture_output=True, text=True, timeout=300
        )
        if target.exists():
            return _build_result("Created Project", target, "success",
                                 f"React project '{name}' created at {target}",
                                 "React Project",
                                 {"framework": "react"})
        return _build_result("Create Project", target, "failed",
                             "create-react-app did not complete successfully",
                             "React Project")
    except subprocess.TimeoutExpired:
        return _build_result("Create Project", target, "failed",
                             "React project creation timed out", "React Project")
    except Exception as e:
        return _build_result("Create Project", target, "failed", str(e), "React Project")


def create_html_project(name, base_dir=None):
    """Create a basic HTML/CSS/JS project."""
    base = Path(base_dir or Path.cwd()).expanduser() / name
    try:
        _ensure_dir(base)
        _ensure_dir(base / "css")
        _ensure_dir(base / "js")
        _ensure_dir(base / "assets")

        # index.html
        index = base / "index.html"
        if not index.exists():
            index.write_text(
                f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name}</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>Welcome to {name}</h1>
    </header>
    <main>
        <p>Your content goes here.</p>
    </main>
    <footer>
        <p>Generated by AMAZON AI Assistant</p>
    </footer>
    <script src="js/main.js"></script>
</body>
</html>""",
                encoding="utf-8"
            )
        # style.css
        css = base / "css" / "style.css"
        if not css.exists():
            css.write_text(
                """* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; }
header { background: #0066cc; color: white; padding: 2rem; text-align: center; }
main { max-width: 800px; margin: 2rem auto; padding: 1rem; }
footer { background: #f8f9fa; text-align: center; padding: 1rem; margin-top: 2rem; }""",
                encoding="utf-8"
            )
        # main.js
        js = base / "js" / "main.js"
        if not js.exists():
            js.write_text(
                f'// {name} - Main JavaScript\ndocument.addEventListener("DOMContentLoaded", function() {{\n    console.log("{name} loaded!");\n}});\n',
                encoding="utf-8"
            )
        return _build_result("Created Project", base, "success",
                             f"HTML project '{name}' created at {base}",
                             "HTML Project",
                             {"framework": "html", "files": ["index.html", "css/style.css", "js/main.js", "assets/"]})
    except Exception as e:
        return _build_result("Create Project", base, "failed", str(e), "HTML Project")


def create_node_project(name, base_dir=None):
    """Create a Node.js project with package.json and basic structure."""
    base = Path(base_dir or Path.cwd()).expanduser() / name
    try:
        _ensure_dir(base)
        # package.json
        pkg = base / "package.json"
        if not pkg.exists():
            pkg.write_text(
                f'{{\n  "name": "{name}",\n  "version": "1.0.0",\n  "description": "Node.js project generated by AMAZON",\n  "main": "index.js",\n  "scripts": {{\n    "start": "node index.js",\n    "dev": "node index.js"\n  }},\n  "keywords": [],\n  "author": "",\n  "license": "ISC"\n}}\n',
                encoding="utf-8"
            )
        # index.js
        index = base / "index.js"
        if not index.exists():
            index.write_text(
                f'const http = require("http");\n\nconst server = http.createServer((req, res) => {{\n    res.writeHead(200, {{ "Content-Type": "text/plain" }});\n    res.end("Hello from {name}!\\n");\n}});\n\nconst PORT = 3000;\nserver.listen(PORT, () => {{\n    console.log(`Server running on port ${{PORT}}`);\n}});\n',
                encoding="utf-8"
            )
        # README
        readme = base / "README.md"
        if not readme.exists():
            readme.write_text(f"# {name}\n\nNode.js project.\n\n## Run\n```bash\nnpm start\n```\n", encoding="utf-8")
        return _build_result("Created Project", base, "success",
                             f"Node.js project '{name}' created at {base}",
                             "Node Project",
                             {"framework": "node", "files": ["package.json", "index.js", "README.md"]})
    except Exception as e:
        return _build_result("Create Project", base, "failed", str(e), "Node Project")


def create_angular_project(name, base_dir=None):
    """Create an Angular project (requires Angular CLI)."""
    base = Path(base_dir or Path.cwd()).expanduser()
    target = base / name
    try:
        result = subprocess.run(
            ["ng", "version"], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            # Fallback: create a basic structure
            _ensure_dir(target / "src")
            (target / "package.json").write_text(
                f'{{\n  "name": "{name}",\n  "version": "0.0.0",\n  "scripts": {{\n    "start": "ng serve"\n  }}\n}}\n',
                encoding="utf-8"
            )
            return _build_result("Created Project", target, "partial",
                                 f"Angular CLI not found. Basic structure created at {target}. Install @angular/cli for full setup.",
                                 "Angular Project",
                                 {"framework": "angular"})

        subprocess.run(
            ["ng", "new", name, "--skip-git", "--skip-install"],
            cwd=str(base), capture_output=True, text=True, timeout=120
        )
        if target.exists():
            return _build_result("Created Project", target, "success",
                                 f"Angular project '{name}' created at {target}",
                                 "Angular Project",
                                 {"framework": "angular"})
        return _build_result("Create Project", target, "failed",
                             "Angular CLI did not complete", "Angular Project")
    except Exception as e:
        return _build_result("Create Project", target, "failed", str(e), "Angular Project")


def create_laravel_project(name, base_dir=None):
    """Create a Laravel project (requires Composer)."""
    base = Path(base_dir or Path.cwd()).expanduser()
    target = base / name
    try:
        result = subprocess.run(
            ["composer", "--version"], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return _build_result("Create Project", target, "failed",
                                 "Composer is not installed. Install Composer to create Laravel projects.",
                                 "Laravel Project")
        subprocess.run(
            ["composer", "create-project", "laravel/laravel", name],
            cwd=str(base), capture_output=True, text=True, timeout=300
        )
        if target.exists():
            return _build_result("Created Project", target, "success",
                                 f"Laravel project '{name}' created at {target}",
                                 "Laravel Project",
                                 {"framework": "laravel"})
        return _build_result("Create Project", target, "failed",
                             "Laravel project creation did not complete", "Laravel Project")
    except Exception as e:
        return _build_result("Create Project", target, "failed", str(e), "Laravel Project")


def create_django_project(name, base_dir=None):
    """Create a Django project (requires Django installed)."""
    base = Path(base_dir or Path.cwd()).expanduser()
    target = base / name
    try:
        result = subprocess.run(
            ["django-admin", "--version"], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return _build_result("Create Project", target, "failed",
                                 "Django is not installed. Run: pip install django",
                                 "Django Project")
        subprocess.run(
            ["django-admin", "startproject", name],
            cwd=str(base), capture_output=True, text=True, timeout=60
        )
        if target.exists():
            return _build_result("Created Project", target, "success",
                                 f"Django project '{name}' created at {target}",
                                 "Django Project",
                                 {"framework": "django"})
        return _build_result("Create Project", target, "failed",
                             "Django project creation did not complete", "Django Project")
    except Exception as e:
        return _build_result("Create Project", target, "failed", str(e), "Django Project")


def create_vue_project(name, base_dir=None):
    """Create a Vue project (requires Node.js)."""
    base = Path(base_dir or Path.cwd()).expanduser()
    target = base / name
    try:
        result = subprocess.run(
            ["node", "--version"], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return _build_result("Create Project", target, "failed",
                                 "Node.js is not installed. Install Node.js to create Vue projects.",
                                 "Vue Project")
        subprocess.run(
            ["npm", "create", "vue@latest", name, "--", "--default"],
            cwd=str(base), capture_output=True, text=True, timeout=120
        )
        if target.exists():
            return _build_result("Created Project", target, "success",
                                 f"Vue project '{name}' created at {target}",
                                 "Vue Project",
                                 {"framework": "vue"})
        # Fallback: create basic structure
        _ensure_dir(target / "src")
        (target / "package.json").write_text(
            f'{{\n  "name": "{name}",\n  "version": "0.0.0"\n}}\n', encoding="utf-8"
        )
        return _build_result("Created Project", target, "partial",
                             f"Basic Vue structure created at {target}",
                             "Vue Project", {"framework": "vue"})
    except Exception as e:
        return _build_result("Create Project", target, "failed", str(e), "Vue Project")


# --- Dispatcher ---

FRAMEWORK_CREATORS = {
    "python": create_python_project,
    "react": create_react_project,
    "html": create_html_project,
    "node": create_node_project,
    "angular": create_angular_project,
    "laravel": create_laravel_project,
    "django": create_django_project,
    "vue": create_vue_project,
    "next": create_react_project,  # Uses similar Node-based approach
}


def create_project(name, framework="python", base_dir=None):
    """Create a project using the appropriate framework scaffolding."""
    framework = (framework or "python").lower().strip()
    creator = FRAMEWORK_CREATORS.get(framework)
    if not creator:
        return _build_result("Create Project", "", "failed",
                             f"Unsupported framework: {framework}. Supported: {', '.join(FRAMEWORK_CREATORS.keys())}",
                             "Project")
    return creator(name, base_dir=base_dir)


# --- Code Snippet Generator ---

SNIPPETS = {
    "python": {
        "class": 'class MyClass:\n    def __init__(self):\n        pass\n\n    def method(self):\n        pass\n',
        "api": 'from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n@app.route("/api/data")\ndef get_data():\n    return jsonify({"status": "ok", "data": []})\n\nif __name__ == "__main__":\n    app.run(debug=True)\n',
        "function": 'def my_function(param):\n    """Description of function."""\n    return param\n',
        "test": 'import unittest\n\nclass TestMyClass(unittest.TestCase):\n    def test_example(self):\n        self.assertEqual(1, 1)\n\nif __name__ == "__main__":\n    unittest.main()\n',
    },
    "javascript": {
        "class": 'class MyClass {\n    constructor() {\n        this.value = null;\n    }\n    method() {\n        return this.value;\n    }\n}\nmodule.exports = MyClass;\n',
        "api": 'const express = require("express");\nconst app = express();\n\napp.get("/api/data", (req, res) => {\n    res.json({ status: "ok", data: [] });\n});\n\napp.listen(3000, () => console.log("Server running on port 3000"));\n',
        "function": 'function myFunction(param) {\n    // Function logic here\n    return param;\n}\nmodule.exports = myFunction;\n',
    },
    "typescript": {
        "interface": 'interface MyInterface {\n    id: number;\n    name: string;\n    isActive: boolean;\n}\n',
        "class": 'class MyClass {\n    private value: string;\n    constructor(value: string) {\n        this.value = value;\n    }\n    getValue(): string {\n        return this.value;\n    }\n}\n',
    },
    "html": {
        "page": '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>Page Title</title>\n</head>\n<body>\n    <h1>Hello World</h1>\n</body>\n</html>\n',
        "form": '<form action="/submit" method="POST">\n    <label for="name">Name:</label>\n    <input type="text" id="name" name="name" required>\n    <label for="email">Email:</label>\n    <input type="email" id="email" name="email" required>\n    <button type="submit">Submit</button>\n</form>\n',
    },
    "sql": {
        "table": 'CREATE TABLE users (\n    id INT PRIMARY KEY AUTO_INCREMENT,\n    username VARCHAR(50) NOT NULL,\n    email VARCHAR(100) UNIQUE NOT NULL,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n',
        "crud": '-- Create\nINSERT INTO users (username, email) VALUES ("john", "john@example.com");\n\n-- Read\nSELECT * FROM users;\n\n-- Update\nUPDATE users SET email = "new@example.com" WHERE id = 1;\n\n-- Delete\nDELETE FROM users WHERE id = 1;\n',
    },
}


def generate_code_snippet(language, snippet_type="class"):
    """Generate a code snippet for a given language and type."""
    language = (language or "python").lower().strip()
    snippet_type = (snippet_type or "class").lower().strip()
    lang_snippets = SNIPPETS.get(language, {})
    if not lang_snippets:
        return {"status": "failed", "message": f"No snippets available for {language}"}
    code = lang_snippets.get(snippet_type)
    if not code:
        available = ", ".join(lang_snippets.keys())
        return {"status": "failed", "message": f"No '{snippet_type}' snippet for {language}. Available: {available}"}
    return {"status": "success", "code": code, "language": language, "type": snippet_type}
