"""
AMAZON AI - Document Generator
Generates structured academic/professional documents (assignments, research proposals, reports).
"""
import os
import re
from pathlib import Path
from datetime import datetime

try:
    import docx
    from docx.shared import Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


def _sanitize_filename(name):
    """Convert any string to a valid filename."""
    sanitized = re.sub(r'[\\/*?:"<>|]', "", name)
    sanitized = re.sub(r'\s+', '_', sanitized)
    return sanitized[:50].strip('_')


def _add_heading(doc, text, level=1):
    """Add a heading to a Word document."""
    if level == 1:
        heading = doc.add_heading(text, level=1)
    elif level == 2:
        heading = doc.add_heading(text, level=2)
    else:
        heading = doc.add_heading(text, level=3)
    return heading


def _add_paragraph(doc, text, bold=False, italic=False):
    """Add a paragraph with optional styling."""
    p = doc.add_paragraph(text)
    if p.runs:
        run = p.runs[0]
        run.font.size = Pt(12)
        run.font.bold = bold
        run.font.italic = italic
    return p


def _add_page_break(doc):
    """Add a page break to the document."""
    doc.add_page_break()


def generate_assignment(topic):
    """Generate a complete assignment document with cover page, introduction, questions, and conclusion."""
    if not DOCX_AVAILABLE:
        return {
            "status": "failed",
            "message": "python-docx is not installed. Install it to create Word documents."
        }

    doc = docx.Document()

    # Cover Page
    doc.add_heading(f"Assignment: {topic.title()}", level=0)
    _add_paragraph(doc, f"Generated by AMAZON AI Assistant", italic=True)
    _add_paragraph(doc, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    _add_page_break(doc)

    # Introduction
    _add_heading(doc, "Introduction")
    intro_text = (
        f"This assignment explores the topic of {topic}. "
        f"The subject matter encompasses various aspects of {topic} that are "
        f"crucial for understanding its significance and application in modern contexts. "
        f"Through this assignment, we will examine key concepts, analyze relevant data, "
        f"and develop comprehensive insights into {topic}."
    )
    _add_paragraph(doc, intro_text)

    # Main Questions/Exercises
    _add_heading(doc, "Questions and Exercises")

    questions = [
        f"1. Define and explain the core principles of {topic}.",
        f"2. Analyze the impact of {topic} on contemporary practices.",
        f"3. Compare and contrast different approaches to {topic}.",
        f"4. Provide real-world examples of {topic} in action.",
        f"5. Evaluate the future implications of {topic}."
    ]

    for q in questions:
        _add_paragraph(doc, q, bold=True)
        _add_paragraph(doc, f"   Discussion: This question requires a detailed examination of {topic} "
                        f"considering theoretical foundations and practical applications. "
                        f"The answer should demonstrate understanding of key concepts and provide "
                        f"evidence-based analysis.")
        doc.add_paragraph()

    # Conclusion
    _add_heading(doc, "Conclusion")
    conclusion_text = (
        f"In conclusion, this assignment has examined {topic} from multiple perspectives. "
        f"The analysis reveals that {topic} represents a significant area of study with "
        f"far-reaching implications. Through careful consideration of the questions presented, "
        f"we have gained valuable insights into the fundamental nature of this subject and "
        f"its relevance in today's context."
    )
    _add_paragraph(doc, conclusion_text)

    return doc


def generate_research_proposal(topic):
    """Generate a complete research proposal with abstract, introduction, literature review, methodology, timeline, and references."""
    if not DOCX_AVAILABLE:
        return {
            "status": "failed",
            "message": "python-docx is not installed. Install it to create Word documents."
        }

    doc = docx.Document()

    # Cover Page
    _add_heading(doc, "Research Proposal", level=0)
    _add_paragraph(doc, f"Title: {topic.title()}")
    _add_paragraph(doc, "Generated by AMAZON AI Assistant", italic=True)
    _add_paragraph(doc, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    _add_page_break(doc)

    # Abstract
    _add_heading(doc, "Abstract")
    abstract_text = (
        f"This research proposal investigates {topic} through a systematic and comprehensive approach. "
        f"The study aims to explore the fundamental aspects of {topic}, analyze current knowledge gaps, "
        f"and propose innovative methodologies for advancing understanding in this field. "
        f"The research will contribute to the existing body of knowledge by providing empirical evidence "
        f"and theoretical frameworks that enhance our comprehension of {topic}."
    )
    _add_paragraph(doc, abstract_text)

    # Introduction
    _add_heading(doc, "1. Introduction")
    intro_text = (
        f"{topic.title()} represents a critical area of investigation in contemporary research. "
        f"This study addresses the growing need for deeper understanding of {topic} and its implications. "
        f"The primary objective of this research is to examine the multifaceted nature of {topic}, "
        f"identify key challenges, and propose evidence-based solutions or insights. "
        f"By conducting a thorough investigation, this research will provide valuable contributions "
        f"to both theoretical knowledge and practical applications."
    )
    _add_paragraph(doc, intro_text)

    # Literature Review
    _add_heading(doc, "2. Literature Review")
    lit_text = (
        f"Previous studies on {topic} have established foundational knowledge in this domain. "
        f"Research by Smith et al. (2020) demonstrated significant correlations between "
        f"{topic} and related factors. Johnson (2019) explored the theoretical underpinnings, "
        f"while Williams (2021) provided empirical analysis of practical implementations. "
        f"However, gaps remain in understanding the long-term effects and optimal approaches "
        f"to {topic}. This research builds upon existing work while addressing these limitations."
    )
    _add_paragraph(doc, lit_text)

    # Research Questions
    _add_heading(doc, "3. Research Questions")
    questions = [
        f"RQ1: What are the primary factors influencing {topic}?",
        f"RQ2: How does {topic} impact related systems or processes?",
        f"RQ3: What methodologies are most effective for studying {topic}?",
        f"RQ4: What are the potential future developments in {topic}?"
    ]
    for q in questions:
        _add_paragraph(doc, q, bold=True)

    # Methodology
    _add_heading(doc, "4. Methodology")
    method_text = (
        f"This study will employ a mixed-methods approach to investigate {topic}. "
        f"Quantitative data will be collected through surveys and statistical analysis, "
        f"while qualitative insights will be gathered via interviews and case studies. "
        f"The research design includes both primary and secondary data sources to ensure "
        f"comprehensive coverage of the topic. Participants will be selected based on "
        f"their expertise and involvement with {topic}."
    )
    _add_paragraph(doc, method_text)

    # Timeline
    _add_heading(doc, "5. Timeline")
    timeline_items = [
        ("Phase 1: Literature Review and Planning", "Weeks 1-2"),
        (f"Phase 2: Data Collection on {topic}", "Weeks 3-5"),
        ("Phase 3: Analysis and Interpretation", "Weeks 6-8"),
        ("Phase 4: Writing and Review", "Weeks 9-10"),
        ("Phase 5: Finalization and Submission", "Weeks 11-12")
    ]
    for item, duration in timeline_items:
        _add_paragraph(doc, f"• {item} ({duration})")

    # References
    _add_heading(doc, "6. References")
    ref_items = [
        f"Johnson, A. (2019). Fundamentals of {topic.title()}. Journal of Research, 45(3), 123-145.",
        f"Smith, B., et al. (2020). Advances in {topic.title()} studies. Research Quarterly, 12(2), 67-89.",
        f"Williams, C. (2021). Practical applications of {topic.title()}. Applied Science Review, 30(4), 234-256.",
        f"Brown, D. (2018). Theoretical frameworks for {topic.title()}. Academic Press."
    ]
    for ref in ref_items:
        _add_paragraph(doc, ref)

    return doc


def generate_report(topic):
    """Generate a structured report with executive summary, introduction, findings, analysis, conclusion, and recommendations."""
    if not DOCX_AVAILABLE:
        return {
            "status": "failed",
            "message": "python-docx is not installed. Install it to create Word documents."
        }

    doc = docx.Document()

    # Cover Page
    _add_heading(doc, f"Report: {topic.title()}", level=0)
    _add_paragraph(doc, "Generated by AMAZON AI Assistant", italic=True)
    _add_paragraph(doc, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    _add_page_break(doc)

    # Executive Summary
    _add_heading(doc, "Executive Summary")
    exec_summary = (
        f"This report provides a comprehensive analysis of {topic}. Key findings indicate "
        f"significant trends and patterns that are shaping the current landscape. "
        f"The report examines critical data points, evaluates performance metrics, "
        f"and presents actionable insights for stakeholders. Based on this analysis, "
        f"strategic recommendations are proposed to optimize outcomes and address identified challenges."
    )
    _add_paragraph(doc, exec_summary)
    doc.add_paragraph()

    # Introduction
    _add_heading(doc, "1. Introduction")
    intro_text = (
        f"The purpose of this report is to analyze and present findings on {topic}. "
        f"In an era where understanding {topic} is increasingly important, this report "
        f"serves as a comprehensive resource for decision-makers and stakeholders. "
        f"The scope of this analysis covers multiple dimensions of {topic}, providing "
        f"a holistic view of the current situation and future prospects."
    )
    _add_paragraph(doc, intro_text)

    # Background
    _add_heading(doc, "2. Background")
    bg_text = (
        f"{topic.title()} has emerged as a significant area of focus due to recent developments "
        f"and changing market conditions. Understanding the background and context of {topic} "
        f"is essential for making informed decisions. This section provides the necessary "
        f"contextual information to frame the subsequent analysis and findings."
    )
    _add_paragraph(doc, bg_text)

    # Findings
    _add_heading(doc, "3. Findings")
    findings = [
        f"Finding 1: {topic} demonstrates measurable impact on key performance indicators.",
        f"Finding 2: Trends in {topic} indicate progressive changes over time.",
        f"Finding 3: Comparative analysis reveals insights when {topic} is benchmarked against standards.",
        f"Finding 4: Stakeholder feedback on {topic} shows overall positive reception with areas for improvement."
    ]
    for f in findings:
        _add_paragraph(doc, f, bold=True)
        _add_paragraph(doc, f"   Analysis: This finding suggests that {topic} plays a crucial role "
                        f"in determining outcomes and should be carefully monitored and managed.")
        doc.add_paragraph()

    # Analysis
    _add_heading(doc, "4. Analysis")
    analysis_text = (
        f"The analysis of {topic} reveals several key insights. First, there is a strong "
        f"correlation between {topic} and desired outcomes. Second, implementation challenges "
        f"can be addressed through strategic planning and resource allocation. "
        f"Third, the data suggests potential for optimization and scaling. "
        f"These findings are supported by empirical evidence and stakeholder input."
    )
    _add_paragraph(doc, analysis_text)

    # Conclusion
    _add_heading(doc, "5. Conclusion")
    conclusion_text = (
        f"This report has provided a thorough examination of {topic}. The analysis confirms "
        f"that {topic} remains a critical factor in achieving desired outcomes. "
        f"The findings demonstrate both opportunities and challenges that must be addressed. "
        f"Moving forward, continued attention to {topic} will be essential for sustained success "
        f"and improvement in this area."
    )
    _add_paragraph(doc, conclusion_text)

    # Recommendations
    _add_heading(doc, "6. Recommendations")
    rec_items = [
        f"1. Implement systematic monitoring of {topic} metrics to track progress and identify issues early.",
        f"2. Develop standardized protocols for managing {topic} to ensure consistency.",
        f"3. Invest in training and resources to enhance capabilities related to {topic}.",
        f"4. Establish regular review cycles to evaluate effectiveness of {topic} initiatives.",
        f"5. Create feedback mechanisms to continuously improve approaches to {topic}."
    ]
    for rec in rec_items:
        _add_paragraph(doc, rec)

    # Appendices
    _add_heading(doc, "7. Appendices")
    _add_paragraph(doc, f"Appendix A: Additional data on {topic}")
    _add_paragraph(doc, f"Appendix B: Detailed methodology and sources")
    _add_paragraph(doc, f"Appendix C: Supplementary charts and graphs")

    return doc


def generate_schedule(topic, person_name=None):
    """Generate a training/work schedule document."""
    if not DOCX_AVAILABLE:
        return {
            "status": "failed",
            "message": "python-docx is not installed. Install it to create Word documents."
        }

    doc = docx.Document()
    
    # Determine schedule title
    if person_name:
        schedule_title = f"{person_name}'s {topic}"
    else:
        schedule_title = topic

    # Cover Page
    _add_heading(doc, f"Training Schedule: {schedule_title.title()}", level=0)
    _add_paragraph(doc, "Generated by AMAZON AI Assistant", italic=True)
    _add_paragraph(doc, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    _add_page_break(doc)

    # Overview
    _add_heading(doc, "Schedule Overview")
    overview_text = (
        f"This document outlines the training schedule for {schedule_title}. "
        f"The schedule is designed to provide comprehensive coverage of all necessary topics "
        f"and ensure effective learning outcomes. Each session is structured to build upon "
        f"previous knowledge and provide practical application opportunities."
    )
    _add_paragraph(doc, overview_text)
    doc.add_paragraph()

    # Training Schedule Table
    _add_heading(doc, "Training Sessions")
    
    sessions = [
        {
            "session": "Session 1: Introduction & Fundamentals",
            "duration": "2 hours",
            "topics": [
                "Overview of key concepts and terminology",
                "Understanding the foundational principles",
                "Setting up the work environment",
                "Q&A and discussion"
            ]
        },
        {
            "session": "Session 2: Core Skills Development",
            "duration": "3 hours",
            "topics": [
                "Hands-on practice with core tools",
                "Step-by-step guided exercises",
                "Common challenges and solutions",
                "Progress assessment"
            ]
        },
        {
            "session": "Session 3: Advanced Techniques",
            "duration": "3 hours",
            "topics": [
                "Advanced features and capabilities",
                "Best practices and optimization",
                "Real-world case studies",
                "Problem-solving scenarios"
            ]
        },
        {
            "session": "Session 4: Practical Application",
            "duration": "4 hours",
            "topics": [
                "Project-based learning exercise",
                "Independent work with guidance",
                "Peer collaboration and review",
                "Feedback and improvement"
            ]
        },
        {
            "session": "Session 5: Assessment & Certification",
            "duration": "2 hours",
            "topics": [
                "Final assessment and evaluation",
                "Review of key learnings",
                "Certification and next steps",
                "Resources for continued learning"
            ]
        },
    ]
    
    for session in sessions:
        _add_heading(doc, session["session"], level=2)
        _add_paragraph(doc, f"Duration: {session['duration']}", bold=True)
        _add_paragraph(doc, "Topics Covered:")
        for topic_item in session["topics"]:
            _add_paragraph(doc, f"• {topic_item}")
        doc.add_paragraph()

    # Learning Objectives
    _add_heading(doc, "Learning Objectives")
    objectives = [
        f"Understand the fundamental concepts and principles of {topic}",
        f"Develop practical skills through hands-on exercises",
        f"Apply knowledge to real-world scenarios",
        f"Demonstrate proficiency through assessment",
        f"Identify resources for continued learning and growth"
    ]
    for obj in objectives:
        _add_paragraph(doc, f"✓ {obj}")

    # Prerequisites
    _add_heading(doc, "Prerequisites")
    prerequisites = [
        "Basic computer literacy",
        "Willingness to learn and practice",
        "Commitment to complete all scheduled sessions",
        "Access to required tools and materials"
    ]
    for prereq in prerequisites:
        _add_paragraph(doc, f"• {prereq}")

    # Notes
    _add_heading(doc, "Additional Notes")
    notes_text = (
        f"This schedule is flexible and can be adjusted based on the learner's pace and needs. "
        f"Regular breaks are recommended between sessions. "
        f"Additional support and resources are available upon request. "
        f"For questions or concerns, please reach out to the training coordinator."
    )
    _add_paragraph(doc, notes_text)

    return doc


def save_document(doc, filename, base_dir=None):
    """Save a Word document to the specified location."""
    if base_dir is None:
        base_dir = Path(os.path.expanduser("~")) / "Desktop"
    else:
        base_dir = Path(base_dir)

    base_dir.mkdir(parents=True, exist_ok=True)

    # Ensure .docx extension
    if not filename.endswith('.docx'):
        filename = filename + '.docx'

    full_path = base_dir / filename

    try:
        doc.save(str(full_path))
        return {
            "status": "success",
            "message": f"Document created: {full_path}",
            "path": str(full_path),
            "name": filename
        }
    except Exception as e:
        return {
            "status": "failed",
            "message": str(e)
        }